export type Phase = "immediate" | "early" | "late";

export type SideEffect = {
  id: string;
  title: string;
  subtitle?: string;
  phase: Phase;
  keywords: string[];
  description: string;
  symptoms?: string[];
  whatToDo?: string[];
  urgent?: string[];
  urgentAction?: "call" | "ed";
};

export const PHASE_LABEL: Record<Phase, string> = {
  immediate: "Immediate · hours to days",
  early: "Early · days to weeks",
  late: "Late · weeks to months",
};

export const SIDE_EFFECTS: SideEffect[] = [
  {
    id: "flu-like",
    title: "Flu-like symptoms",
    phase: "immediate",
    keywords: ["flu", "fever", "chills", "sweats", "muscle", "joint", "cough", "headache", "rituximab"],
    description: "Caused by rituximab.",
    symptoms: ["A fever", "Chills or sweats", "Muscle and joint pain", "A cough", "Headaches"],
    urgent: ["Tell your doctor or nurse immediately if you get any of these symptoms."],
    urgentAction: "call",
  },
  {
    id: "headache",
    title: "Headache",
    phase: "immediate",
    keywords: ["headache", "migraine", "head pain"],
    description: "Mild headaches are common.",
    whatToDo: ["You can take paracetamol for a headache."],
    urgent: ["Go to the nearest Emergency Department if the headache is very bad and not helped by pain medication."],
    urgentAction: "ed",
  },
  {
    id: "allergic-reaction",
    title: "Allergic reaction",
    phase: "immediate",
    keywords: ["allergy", "allergic", "anaphylaxis", "rash", "itch", "wheeze", "dizzy", "faint"],
    description: "Allergic reactions are uncommon but can be life-threatening.",
    symptoms: [
      "Feeling unwell during the infusion or shortly after",
      "Fever, shivers or shakes",
      "Feeling dizzy, faint, confused or anxious",
      "Wheezing or difficulty breathing",
      "Rash, itch or redness of the face",
    ],
    urgent: [
      "While in hospital: tell your doctor or nurse immediately.",
      "After you leave: contact your doctor/nurse immediately or go to the nearest ED.",
    ],
    urgentAction: "ed",
  },
  {
    id: "injection-site",
    title: "Injection-site reaction",
    phase: "immediate",
    keywords: ["injection", "cannula", "site", "redness", "swelling", "bruising"],
    description: "Pain, redness, swelling or bruising at the injection site. Usually not serious.",
    urgent: ["Tell your doctor or nurse if you notice redness or pain during or after treatment."],
    urgentAction: "call",
  },
  {
    id: "nausea-vomiting",
    title: "Nausea and vomiting",
    phase: "immediate",
    keywords: ["nausea", "vomit", "sick", "throw up", "queasy"],
    description: "You may feel sick or vomit.",
    whatToDo: [
      "Drink plenty of fluids (unless fluid restricted).",
      "Eat small meals more frequently.",
      "Try food that doesn't need much preparation.",
      "Try bland foods like dry biscuits or toast.",
      "Gentle exercise can help.",
      "Anti-sickness medication is usually not needed but may help some people.",
    ],
    urgent: ["Go to ED if vomiting is uncontrolled, or you feel dizzy or light-headed."],
    urgentAction: "ed",
  },
  {
    id: "taste-smell",
    title: "Taste and smell changes",
    phase: "immediate",
    keywords: ["taste", "smell", "metallic", "food"],
    description: "Food may lose its taste or taste different. This is likely to go away with time.",
    whatToDo: [
      "Keep up mouth care regularly.",
      "Chew sugar-free gum or eat sugar-free mints.",
      "Add flavour to your food with sauces and herbs.",
    ],
  },
  {
    id: "confusion-immediate",
    title: "Confusion",
    phase: "immediate",
    keywords: ["confusion", "confused", "disoriented"],
    description: "Sudden confusion can be a sign of something serious during or after treatment.",
    urgent: ["Tell your doctor or nurse immediately. If after discharge, go to the nearest ED."],
    urgentAction: "ed",
  },

  {
    id: "neutropenia",
    title: "Infection risk (neutropenia)",
    phase: "early",
    keywords: ["infection", "neutropenia", "neutrophils", "white cells", "fever", "temperature"],
    description: "This treatment lowers your white blood cells (neutrophils). Low neutrophils means you're at greater risk of infection — this can be life-threatening.",
    whatToDo: [
      "Wash your hands often.",
      "Keep a thermometer at home; check your temperature regularly and whenever you feel unwell.",
      "Keep up mouth care.",
      "Check your central line site daily for redness, pus or swelling.",
      "Limit contact with people who are sick.",
    ],
    urgent: [
      "Temperature of 38°C or higher",
      "Chills, shivers, sweats or shakes",
      "Sore throat or cough",
      "Uncontrolled diarrhoea",
      "Shortness of breath",
      "Fast heartbeat",
      "Feeling unwell even without a temperature",
    ],
    urgentAction: "ed",
  },
  {
    id: "thrombocytopenia",
    title: "Low platelets (thrombocytopenia)",
    phase: "early",
    keywords: ["platelets", "bleeding", "bruising", "thrombocytopenia", "clot"],
    description: "Treatment lowers the platelets in your blood. When platelets are low you're at greater risk of bleeding and bruising.",
    whatToDo: [
      "Try not to bruise or cut yourself.",
      "Avoid contact sport or vigorous exercise.",
      "Clear your nose by blowing gently.",
      "Avoid constipation.",
      "Brush your teeth with a soft toothbrush.",
      "Don't take aspirin, ibuprofen or similar anti-inflammatories unless your doctor says to.",
    ],
    urgent: ["Uncontrolled bleeding — go to ED."],
    urgentAction: "ed",
  },
  {
    id: "appetite-loss",
    title: "Appetite loss (anorexia)",
    phase: "early",
    keywords: ["appetite", "hungry", "eating", "weight loss"],
    description: "You may not feel like eating.",
    whatToDo: [
      "Try to avoid drinking fluids at meal times.",
      "Eat small meals or snacks regularly throughout the day.",
      "Eat food high in protein and calories.",
      "Ask to speak to a dietitian if worried about intake or losing weight.",
    ],
  },
  {
    id: "conjunctivitis",
    title: "Eye problems (conjunctivitis)",
    phase: "early",
    keywords: ["eye", "eyes", "red", "itchy", "conjunctivitis"],
    description: "Your eyes may become itchy, red and swollen.",
    whatToDo: ["Try not to touch your eyes.", "Wash your hands regularly."],
    urgent: ["Tell your doctor or nurse — you may need antibiotic eye drops."],
    urgentAction: "call",
  },
  {
    id: "fatigue",
    title: "Tiredness and lack of energy (fatigue)",
    phase: "early",
    keywords: ["fatigue", "tired", "exhausted", "sleepy", "low energy"],
    description: "You may feel very tired, have no energy, sleep a lot, and not be able to do normal activities.",
    whatToDo: [
      "Don't drive or operate machinery while feeling tired.",
      "Nap in short periods (only about 1 hour at a time).",
      "Prioritise your tasks to make the best use of your energy.",
      "Eat a well-balanced diet and drink plenty of fluids (unless restricted).",
      "Try some gentle exercise daily.",
      "Allow friends and family to help.",
    ],
    urgent: ["Tell your doctor or nurse if fatigue is new or much worse."],
    urgentAction: "call",
  },
  {
    id: "diarrhoea",
    title: "Diarrhoea",
    phase: "early",
    keywords: ["diarrhoea", "diarrhea", "loose", "bowels", "stool", "poo"],
    description: "Bowel motions that are more frequent or more liquid. May also come with bloating, cramping or pain.",
    whatToDo: [
      "Take anti-diarrhoeal medication as directed.",
      "Drink plenty of fluids (unless restricted).",
      "Eat and drink small amounts more often.",
      "Avoid spicy foods, dairy, high-fibre foods and coffee.",
    ],
    urgent: ["Go to ED if diarrhoea is uncontrolled, if you have 4+ loose motions per day, or if you feel dizzy/light-headed."],
    urgentAction: "ed",
  },
  {
    id: "skin-rash",
    title: "Skin rash",
    phase: "early",
    keywords: ["rash", "skin", "itch", "dry", "bumpy"],
    description: "Red, bumpy rash and dry, itchy skin.",
    whatToDo: [
      "Moisturise with a gentle non-perfumed cream (sorbolene or aqueous).",
      "Don't scratch your skin.",
      "Protect your skin from sun — clothing, wide-brimmed hat, sunglasses, SPF 50+.",
      "Talk to your doctor/nurse about other ways to manage the rash.",
    ],
  },
  {
    id: "severe-skin",
    title: "Severe skin reaction",
    phase: "early",
    keywords: ["severe rash", "blister", "skin", "mouth ulcer", "SJS"],
    description: "One of your drugs can cause a severe skin reaction. It may start as a mild rash and develop into more serious skin problems.",
    symptoms: [
      "Feeling generally unwell",
      "Fever, aches, fatigue, cough",
      "Blocked or runny nose, sore throat, sore eyes",
      "Painful, itchy rash — sometimes with small blisters",
      "Mouth ulcers, pain in mouth/throat, difficulty eating or swallowing",
    ],
    urgent: ["Go to ED immediately if you get any of the above."],
    urgentAction: "ed",
  },

  {
    id: "anaemia",
    title: "Low red blood cells (anaemia)",
    phase: "late",
    keywords: ["anaemia", "anemia", "pale", "dizzy", "tired", "haemoglobin"],
    description: "You may feel dizzy, light-headed, tired and appear more pale than usual.",
    whatToDo: ["Tell your doctor or nurse — you might need a blood transfusion."],
    urgent: ["Go to ED if you have chest pain, trouble breathing, or feel like your heart is racing."],
    urgentAction: "ed",
  },
  {
    id: "hair-thinning",
    title: "Hair thinning",
    phase: "late",
    keywords: ["hair", "thinning", "loss", "scalp", "dry hair"],
    description: "Hair may become dry, break easily, and some may fall out.",
    whatToDo: [
      "Use a gentle shampoo and a soft hairbrush.",
      "Take care with hairspray, dye, bleaches, perms.",
      "Protect your scalp from cold with a hat or scarf, and from sun with a hat + SPF 50+.",
      "Ask about the Look Good Feel Better program (www.lgfb.org.au).",
    ],
  },
  {
    id: "pml",
    title: "Changes in brain function (PML)",
    subtitle: "Progressive multifocal leukoencephalopathy",
    phase: "late",
    keywords: ["pml", "brain", "speech", "vision", "confusion", "memory", "seizure", "weakness"],
    description: "This treatment can affect your central nervous system. It can be very serious.",
    symptoms: [
      "Trouble with speech or vision",
      "Confusion or memory loss",
      "Changes in personality",
      "Weakness in arms or legs",
      "Poor balance or coordination",
      "Seizures",
    ],
    urgent: ["Go to ED immediately if you get any of these symptoms."],
    urgentAction: "ed",
  },
  {
    id: "second-cancer",
    title: "Developing a second cancer",
    phase: "late",
    keywords: ["second cancer", "secondary", "malignancy"],
    description: "There is a risk of developing a second cancer as a result of this treatment. It's uncommon and may not appear until some time after treatment finishes.",
    whatToDo: ["Discuss the benefits and risks of treatment with your doctor if you have concerns."],
  },
];
